### ISSUE TITLE
Sound card name is hardcoded

### ISSUE THREAD

**Issue by rafael2k** [maemo-leste/maemo-statusmenu-volume#3]
For PinePhone, for example, an user needs to take the action described in:
https://leste.maemo.org/PinePhone#Volume_Applet

**Comment by MerlijnWajer** [comment]
See https://github.com/maemo-leste/maemo-statusmenu-volume/pull/4

**Comment by freemangordon** [comment]
fixed in https://github.com/maemo-leste/maemo-statusmenu-volume/commit/cc2416c5b97a6d63addb92d8df3e91dbed983b9b
